// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type GeneralDocumentDataSlicesSlice =
  | HeroSlice
  | AccordionSlice
  | CallToActionSlice
  | ContentSlice;

/**
 * Content for General documents
 */
interface GeneralDocumentData {
  /**
   * Slice Zone field in *General*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: general.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GeneralDocumentDataSlicesSlice> /**
   * Meta Description field in *General*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: general.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *General*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *General*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: general.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * General document from Prismic
 *
 * - **API ID**: `general`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GeneralDocumentData>,
    "general",
    Lang
  >;

type HomeDocumentDataSlicesSlice = CallToActionSlice | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LayoutDocumentDataSlicesSlice = NavbarItemSlice;

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Contact CTA Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.contact_cta_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_cta_label: prismic.KeyTextField;

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type NavbarsubmenuDocumentDataSlicesSlice = NavbarSubmenuItemSlice;

/**
 * Content for NavbarSubmenu documents
 */
interface NavbarsubmenuDocumentData {
  /**
   * Slice Zone field in *NavbarSubmenu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbarsubmenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarsubmenuDocumentDataSlicesSlice>;
}

/**
 * NavbarSubmenu document from Prismic
 *
 * - **API ID**: `navbarsubmenu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarsubmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavbarsubmenuDocumentData>,
    "navbarsubmenu",
    Lang
  >;

export type AllDocumentTypes =
  | GeneralDocument
  | HomeDocument
  | LayoutDocument
  | NavbarsubmenuDocument;

/**
 * Primary content in *Accordion → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * Title field in *Accordion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Accordion → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Accordion → Items*
 */
export interface AccordionSliceDefaultItem {
  /**
   * Question field in *Accordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Accordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  Simplify<AccordionSliceDefaultItem>
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background field in *CallToAction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: The color of the background
   * - **Default Value**: primary
   * - **API ID Path**: call_to_action.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"primary" | "secondary", "filled">;
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceDefaultItem {
  /**
   * ActionLabel field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].actionlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  actionlabel: prismic.KeyTextField;

  /**
   * ActionLink field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].actionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  actionlink: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  Simplify<CallToActionSliceDefaultItem>
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceSplitImagePrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background field in *CallToAction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: The color of the section background
   * - **Default Value**: primary
   * - **API ID Path**: call_to_action.primary.background
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background: prismic.SelectField<"primary" | "secondary", "filled">;

  /**
   * Image field in *CallToAction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceSplitImageItem {
  /**
   * ActionLabel field in *CallToAction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].actionlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  actionlabel: prismic.KeyTextField;

  /**
   * ActionLink field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].actionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  actionlink: prismic.LinkField;
}

/**
 * Split Image variation for CallToAction Slice
 *
 * - **API ID**: `splitImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceSplitImage = prismic.SharedSliceVariation<
  "splitImage",
  Simplify<CallToActionSliceSplitImagePrimary>,
  Simplify<CallToActionSliceSplitImageItem>
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceSplitImage;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Content → Items*
 */
export interface ContentSliceDefaultItem {
  /**
   * ActionText field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].actiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  actiontext: prismic.KeyTextField;

  /**
   * ActionLink field in *Content → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].actionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  actionlink: prismic.LinkField;
}

/**
 * Card Right variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  Simplify<ContentSliceDefaultItem>
>;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceCardLeftPrimary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Background Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Content → Items*
 */
export interface ContentSliceCardLeftItem {
  /**
   * ActionText field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].actiontext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  actiontext: prismic.KeyTextField;

  /**
   * ActionLink field in *Content → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].actionlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  actionlink: prismic.LinkField;
}

/**
 * Card Left variation for Content Slice
 *
 * - **API ID**: `cardLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceCardLeft = prismic.SharedSliceVariation<
  "cardLeft",
  Simplify<ContentSliceCardLeftPrimary>,
  Simplify<ContentSliceCardLeftItem>
>;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceColumnsPrimary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Content → Items*
 */
export interface ContentSliceColumnsItem {
  /**
   * Column Title field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_title: prismic.KeyTextField;

  /**
   * Column Description field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_description: prismic.KeyTextField;

  /**
   * Column Image field in *Content → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  column_image: prismic.ImageField<never>;
}

/**
 * Columns - 2 variation for Content Slice
 *
 * - **API ID**: `columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceColumns = prismic.SharedSliceVariation<
  "columns",
  Simplify<ContentSliceColumnsPrimary>,
  Simplify<ContentSliceColumnsItem>
>;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceColumns3Primary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Background Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Content → Items*
 */
export interface ContentSliceColumns3Item {
  /**
   * Column Title field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_title: prismic.KeyTextField;

  /**
   * Column Description field in *Content → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_description: prismic.KeyTextField;

  /**
   * Column Image field in *Content → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].column_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  column_image: prismic.ImageField<never>;
}

/**
 * Columns - 3 variation for Content Slice
 *
 * - **API ID**: `columns3`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceColumns3 = prismic.SharedSliceVariation<
  "columns3",
  Simplify<ContentSliceColumns3Primary>,
  Simplify<ContentSliceColumns3Item>
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation =
  | ContentSliceDefault
  | ContentSliceCardLeft
  | ContentSliceColumns
  | ContentSliceColumns3;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *NavbarItem → Primary*
 */
export interface NavbarItemSliceDefaultPrimary {
  /**
   * Label field in *NavbarItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *NavbarItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Single Link variation for NavbarItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *NavbarItem → Primary*
 */
export interface NavbarItemSliceWithSubmenuPrimary {
  /**
   * Label field in *NavbarItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *NavbarItem → Items*
 */
export interface NavbarItemSliceWithSubmenuItem {
  /**
   * Label field in *NavbarItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_item.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *NavbarItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_item.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * With Submenu variation for NavbarItem Slice
 *
 * - **API ID**: `withSubmenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarItemSliceWithSubmenu = prismic.SharedSliceVariation<
  "withSubmenu",
  Simplify<NavbarItemSliceWithSubmenuPrimary>,
  Simplify<NavbarItemSliceWithSubmenuItem>
>;

/**
 * Slice variation for *NavbarItem*
 */
type NavbarItemSliceVariation =
  | NavbarItemSliceDefault
  | NavbarItemSliceWithSubmenu;

/**
 * NavbarItem Shared Slice
 *
 * - **API ID**: `navbar_item`
 * - **Description**: NavbarItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarItemSlice = prismic.SharedSlice<
  "navbar_item",
  NavbarItemSliceVariation
>;

/**
 * Primary content in *NavbarSubmenuItem → Primary*
 */
export interface NavbarSubmenuItemSliceDefaultPrimary {
  /**
   * Label field in *NavbarSubmenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_submenu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *NavbarSubmenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar_submenu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavbarSubmenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSubmenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSubmenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavbarSubmenuItem*
 */
type NavbarSubmenuItemSliceVariation = NavbarSubmenuItemSliceDefault;

/**
 * NavbarSubmenuItem Shared Slice
 *
 * - **API ID**: `navbar_submenu_item`
 * - **Description**: NavbarSubmenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSubmenuItemSlice = prismic.SharedSlice<
  "navbar_submenu_item",
  NavbarSubmenuItemSliceVariation
>;

/**
 * Primary content in *Team → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Title field in *Team → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Team → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * Full Name field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].full_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name: prismic.KeyTextField;

  /**
   * Job Title field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Job Description field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].job_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_description: prismic.KeyTextField;

  /**
   * Image field in *Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GeneralDocument,
      GeneralDocumentData,
      GeneralDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      NavbarsubmenuDocument,
      NavbarsubmenuDocumentData,
      NavbarsubmenuDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimary,
      AccordionSliceDefaultItem,
      AccordionSliceVariation,
      AccordionSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceDefaultItem,
      CallToActionSliceSplitImagePrimary,
      CallToActionSliceSplitImageItem,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceSplitImage,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceDefaultItem,
      ContentSliceCardLeftPrimary,
      ContentSliceCardLeftItem,
      ContentSliceColumnsPrimary,
      ContentSliceColumnsItem,
      ContentSliceColumns3Primary,
      ContentSliceColumns3Item,
      ContentSliceVariation,
      ContentSliceDefault,
      ContentSliceCardLeft,
      ContentSliceColumns,
      ContentSliceColumns3,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      NavbarItemSlice,
      NavbarItemSliceDefaultPrimary,
      NavbarItemSliceWithSubmenuPrimary,
      NavbarItemSliceWithSubmenuItem,
      NavbarItemSliceVariation,
      NavbarItemSliceDefault,
      NavbarItemSliceWithSubmenu,
      NavbarSubmenuItemSlice,
      NavbarSubmenuItemSliceDefaultPrimary,
      NavbarSubmenuItemSliceVariation,
      NavbarSubmenuItemSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimary,
      TeamSliceDefaultItem,
      TeamSliceVariation,
      TeamSliceDefault,
    };
  }
}
