// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact: dynamic(() => import("./Contact")),
  content: dynamic(() => import("./Content")),
  footer_column: dynamic(() => import("./FooterColumn")),
  hero: dynamic(() => import("./Hero")),
  navbar_item: dynamic(() => import("./NavbarItem")),
  team: dynamic(() => import("./Team")),
};
