// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  call_to_action: dynamic(() => import("./CallToAction")),
  content: dynamic(() => import("./Content")),
  hero: dynamic(() => import("./Hero")),
  navbar_item: dynamic(() => import("./NavbarItem")),
  navbar_submenu_item: dynamic(() => import("./NavbarSubmenuItem")),
  team: dynamic(() => import("./Team")),
};
