// Code generated by Slice Machine. DO NOT EDIT.

import { lazy } from "react";

export const components = {
  accordion: lazy(() => import("./Accordion")),
  call_to_action: lazy(() => import("./CallToAction")),
  contact: lazy(() => import("./Contact")),
  content: lazy(() => import("./Content")),
  footer_column: lazy(() => import("./FooterColumn")),
  hero: lazy(() => import("./Hero")),
  navbar_item: lazy(() => import("./NavbarItem")),
  team: lazy(() => import("./Team")),
};
